---
- name: clipnotify install
  tags:
    - clipnotify
  block:
    - name: install
      ansible.builtin.make:
        target: install
        chdir: "{{ playbook_dir }}/clipnotify"
      become: yes
