#!/bin/sh

. "$HOME"/.local/bin/internal

volume() {
    master=$(amixer get Master)
    perc=$(echo "$master" | grep -o '[0-9]*%' | head -n1)
    icon=$(echo "$master" | grep -q '\[off\]' && echo "󰖁" || echo "󰕾")
    echo "$icon" "$perc"
}

volume
