#!/bin/sh

main() {
  case $1 in
    inc)
      increase_brightness
      exit 0
      ;;
    dec)
      decrease_brightness
      exit 0
      ;;
    *)
      help
      exit 1
      ;;
  esac
}

get_external_displays() {
  ddcutil detect 2>/dev/null | awk '/^Display/ {print $2}'
}

change_brightness() {
  # Internal display
  brightnessctl set 5%"$1"

  # External displays
  displays=$(get_external_displays)

  for disp in $displays; do
    ddcutil --display "$disp" setvcp 10 "$1" 5
  done
}

increase_brightness() {
  change_brightness + && progress_bar
}

decrease_brightness() {
  change_brightness - && progress_bar
}

progress_bar() {
  notify-send "Brightness" -h string:x-dunst-stack-tag:brightness -h int:value:"$(get_brightness_percentage)"
}

get_brightness_percentage() {
  displays=$(get_external_displays)

  if [ -z "$displays" ]; then
    percentage=$(($(brightnessctl get) * 100 / $(brightnessctl max)))
  else
    display=$(printf '%s\n' "$displays" | awk 'NR == 1 {print; exit}')
    percentage=$(ddcutil --display "$display" getvcp 10 2>/dev/null |
      awk -F'[=,]' '/current value/ {print $2 * 100 / $4; exit}')
  fi

  echo "$percentage"
}

help() {
  echo "Usage: brightness [inc|dec]"
  echo "  inc       increase brightness"
  echo "  dec       decrease brightness"
}

main "$1"
