#!/bin/sh

main() {
  case $1 in
    inc)
      increase_brightness
      exit 0
      ;;
    dec)
      decrease_brightness
      exit 0
      ;;
    help)
      help
      exit 0
      ;;
    *)
      help
      exit 1
      ;;
  esac
}

change_brightness() {
  # Internal display
  brightnessctl set 5%"$1"

  # External displays
  displays=$(ddcutil detect 2>/dev/null | awk '/^Display/ {print $2}')

  for disp in $displays; do
    ddcutil --display "$disp" setvcp 10 "$1" 5
  done
}

increase_brightness() {
  change_brightness +
  progress_bar
}

decrease_brightness() {
  change_brightness -
  progress_bar
}

progress_bar() {
  notify-send "Brightness" -h string:x-dunst-stack-tag:brightness -h int:value:"$(get_brightness_percentage)"
}

get_brightness_percentage() {
  echo $(($(brightnessctl get) * 100 / $(brightnessctl max))) || ddcutil getvcp 10
}

help() {
  echo "Usage: brightness [inc|dec|help]"
  echo "  inc       increase brightness"
  echo "  dec       decrease brightness"
  echo "  help      print help"
}

main "$1"
