#!/bin/sh
# Change the power mode with powerprofilesctl

get_available_power_modes() {
  # cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
  echo "performance balanced power-saver"
}

send_notification() {
  notify-send -h string:x-dunst-stack-tag:power "Power profile" "Set to $1"
}

set_power() {
  power_mode="$(get_available_power_modes | tr ' ' '\n' | dmenu -p "Power mode:")"

  # exit if dmenu is cancelled or nothing is selected
  if [ $? -eq 130 ] || [ -z "$power_mode" ]; then
    exit 130
  fi

  # echo "$power_mode" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
  powerprofilesctl set "$power_mode" && send_notification "$power_mode"
}

get() {
  profile=$(powerprofilesctl list | awk '/\*/ {print $2}')
  case $profile in
    "balanced:")
      echo " "
      ;;
    "performance:")
      echo " "
      ;;
    "power-saver:")
      echo " "
      ;;
  esac
}

help() {
  echo "Usage: power [set|get]"
  echo "  set   set power mode"
  echo "  get   get current power mode"
}

main() {
  case $1 in
    set)
      set_power
      exit 0
      ;;
    get)
      get
      exit 0
      ;;
    *)
      help
      exit 1
      ;;
  esac
}

main "$1"
