#!/bin/sh

main() {
  case $1 in
    status)
      status
      exit 0
      ;;
    switch)
      switch
      exit 0
      ;;
    *)
      help
      exit 1
      ;;
  esac
}

send_notification() {
  notify-send -h string:x-dunst-stack-tag:vpn "Vpn" "$1"
}

switch() {
  if ! command -v tailscale >/dev/null; then
    send_notification "Tailscale is not installed"
    exit 1
  fi

  if tailscale status >/dev/null; then
    tailscale down
    send_notification "Tailscale deactivated"
  else
    tailscale up
    send_notification "Tailscale activated"
  fi
}

status() {
  if ! ip route show default | grep default >/dev/null; then
    echo "󰍸"
  elif command -v tailscale >/dev/null && tailscale status >/dev/null; then
    echo "󰒄"
  else
    echo "󰐚"
  fi
}

help() {
  echo "Usage: vpn_control [status|switch|help]"
  echo "  status    show vpn status"
  echo "  switch    switch vpn on/off"
  echo "  help      print help"
}

main "$1"
