---
- name: add Thorium APT repository
  ansible.builtin.apt_repository:
    repo: "deb [trusted=yes arch=amd64] https://dl.thorium.rocks/debian/ stable main"
    state: present
  become: yes

- name: update package list
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: install Thorium
  ansible.builtin.apt:
    name: thorium-browser
    state: present
  become: yes
