---
- name: dwm install
  tags:
    - dwm
  block:
    - name: copy config.def.h
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/dwm/config.def.h"
        dest: "{{ playbook_dir }}/dwm/config.h"
      become: yes
    - name: install
      ansible.builtin.make:
        target: "{{ item }}"
        chdir: "{{ playbook_dir }}/dwm"
      loop:
        - clean
        - install
      become: yes

- name: symlink config
  tags:
    - dwm
  block:
    - name: create config directory
      ansible.builtin.file:
        path: ~/.dwm
        state: directory

    - name: symlink config
      ansible.builtin.file:
        src: "{{ role_path }}/files/dwm/autostart.sh"
        dest: ~/.dwm/autostart.sh
        state: link
        force: yes
      when: ansible_facts['os_family'] == 'Debian'

    # - name: symlink config
    #   ansible.builtin.file:
    #     src: "{{ role_path }}/files/debian12/autostart.sh"
    #     dest: ~/.dwm/autostart.sh
    #     state: link
    #     force: yes
    #   when: ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] == "12"

    - name: desktop entry
      ansible.builtin.copy:
        src: "{{ role_path }}/files/desktop/dwm.desktop"
        dest: "/usr/share/xsessions/dwm.desktop"
        mode: 0644
      become: yes
