---
- name: dwm install
  tags:
    - dwm
  block:
    - name: copy config.def.h
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/dwm/config.def.h"
        dest: "{{ playbook_dir }}/dwm/config.h"
      become: yes
    - name: install
      ansible.builtin.make:
        target: "{{ item }}"
        chdir: "{{ playbook_dir }}/dwm"
      loop:
        - clean
        - install
      become: yes
