---
- name: dwm install
  tags:
    - dwm
  block:
    - name: copy config.def.h
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/dwm/config.def.h"
        dest: "{{ playbook_dir }}/dwm/config.h"
      become: yes
    - name: install
      ansible.builtin.make:
        target: "{{ item }}"
        chdir: "{{ playbook_dir }}/dwm"
      loop:
        - clean
        - install
      become: yes

- name: symlink config
  tags:
    - dwm
  block:
    - name: create config directory
      ansible.builtin.file:
        path: ~/.dwm
        state: directory

    - name: symlink config
      ansible.builtin.file:
        src: "{{ role_path }}/files/dwm"
        dest: ~/.dwm
        state: link
        force: yes
