---
- name: slock install
  tags:
    - slock
  block:
    - name: copy config.def.h
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/slock/config.def.h"
        dest: "{{ playbook_dir }}/slock/config.h"
      become: yes
    - name: install
      ansible.builtin.make:
        target: "{{ item }}"
        chdir: "{{ playbook_dir }}/slock"
      loop:
        - clean
        - install
      become: yes
