- name: config | linkg
  tags:
    - config
  block:
    - name: desktop entry
      ansible.builtin.file:
        src: "{{ role_path }}/files/desktop/dwm.desktop"
        dest: "/usr/share/xsessions/dwm.desktop"
        state: link
        force: yes
      become: yes
    - name: touchpad config
      ansible.builtin.file:
        src: "{{ role_path }}/files/touchpad/30-touchpad.conf"
        dest: "/etc/X11/xorg.conf.d/30-touchpad.conf"
        state: link
        force: yes
      become: yes
