---
- name: install
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:
    - git
    - make
    - gcc
    - libx11-dev
    - libxft-dev
    - libxinerama-dev
    - libxrandr-dev
    - libxfixes-dev
    - xorg
    - x11-xserver-utils
    - libnotify-bin
    - lm-sensors
    - sysstat
    - acpi
    - nitrogen
    - picom
    - arandr
    - autorandr
    - mpv
    - dunst
    - gnome-keyring
    - alacritty
    - flameshot
    - thunar
    - brightnessctl
    - xsel
    - zip
    - unzip
    - onboard
  become: yes

- name: make brightnessctl runable without sudo
  ansible.builtin.shell: 'sudo chmod +s "$(which brightnessctl)"'
