---
- name: dwmblocks install
  tags:
    - dwmblocks
  block:
    - name: copy blocks.def.h
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/dwmblocks/blocks.def.h"
        dest: "{{ playbook_dir }}/dwmblocks/blocks.h"
      become: yes
    - name: install
      ansible.builtin.make:
        target: "{{ item }}"
        chdir: "{{ playbook_dir }}/dwmblocks/"
      loop:
        - clean
        - install
      become: yes
    - name: Create symlinks for scripts
      ansible.builtin.find:
        paths: "{{ role_path }}/files/scripts"
        file_type: file
      register: scripts_files
    - name: symlink scripts to /usr/local/bin
      ansible.builtin.file:
        src: "{{ item.path }}"
        dest: "/usr/local/bin/{{ item.path | basename }}"
        state: link
      loop: "{{ scripts_files.files }}"
      become: yes
