---
- name: dmenu install
  tags:
    - dmenu
  block:
    - name: copy config.def.h
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/dmenu/config.def.h"
        dest: "{{ playbook_dir }}/dmenu/config.h"
      become: yes
    - name: install
      ansible.builtin.make:
        target: "{{ item }}"
        chdir: "{{ playbook_dir }}/dmenu"
      loop:
        - clean
        - install
      become: yes
