---
- name: slstatus install
  tags:
    - slstatus
  block:
    - name: copy config.def.h
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/slstatus/config.def.h"
        dest: "{{ playbook_dir }}/slstatus/config.h"
      become: yes
    - name: install
      ansible.builtin.make:
        target: "{{ item }}"
        chdir: "{{ playbook_dir }}/slstatus/"
      loop:
        - clean
        - install
      become: yes
