---
- name: install
  tags:
    - fonts
  block:
  - name: create directory
    ansible.builtin.file:
      path: ~/.fonts/zip
      state: directory

  - name: download hack font
    ansible.builtin.get_url:
      url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/Hack.zip
      dest: ~/.fonts/zip/Hack.zip

  - name: unarchive hack font
    ansible.builtin.unarchive:
      src: ~/.fonts/zip/Hack.zip
      dest: ~/.fonts
